# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_client_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cidr_block', models.CharField(max_length=20)),
                ('region', models.CharField(default='sa-east-1', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cidr_block', models.CharField(max_length=20)),
                ('region', models.CharField(default='sa-east-1', max_length=35)),
                ('client_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.AddField(
            model_name='subnet',
            name='vpc_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.Vpc'),
        ),
    ]
