# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpc',
            name='description',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
