# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_subnet_client_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='description',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
