# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_client_alias'),
        ('cloud', '0004_subnet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='N/A', max_length=100)),
                ('client_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('vpc_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.Vpc')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGroup_Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='N/A', max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('from_port', models.CharField(max_length=8)),
                ('to_port', models.CharField(max_length=8)),
                ('cidr', models.CharField(max_length=20)),
                ('securityGroup_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.SecurityGroup')),
            ],
        ),
    ]
