# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_securitygroup_securitygroup_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroup_Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(default='N/A', max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('from_port', models.CharField(max_length=8)),
                ('to_port', models.CharField(max_length=8)),
                ('cidr', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='securitygroup_rules',
            name='securityGroup_fk',
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.DeleteModel(
            name='SecurityGroup_Rules',
        ),
        migrations.AddField(
            model_name='securitygroup_rule',
            name='securityGroup_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.SecurityGroup'),
        ),
    ]
