# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_auto_20171027_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitygroup_rule',
            old_name='from_port',
            new_name='port',
        ),
        migrations.RemoveField(
            model_name='securitygroup_rule',
            name='to_port',
        ),
    ]
