# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_auto_20171028_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConfigurationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(default='N/A', max_length=100)),
                ('securityGroup_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.SecurityGroup')),
                ('subent_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.Subnet')),
                ('vpc_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cloud.Vpc')),
            ],
        ),
    ]
