# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_cloudconfigurationgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='cloudconfigurationgroup',
            old_name='subent_fk',
            new_name='subnet_fk',
        ),
    ]
