# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_client_alias'),
        ('cloud', '0009_auto_20171030_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudrole',
            name='client_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
