# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_service', '0002_auto_20171006_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='ca_crt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
