# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_service', '0003_registry_ca_crt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='ca_crt',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
