# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170822_1530'),
        ('network', '0005_network_network_bridge_name'),
        ('micro_service', '0004_auto_20171006_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container_catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='N/A', max_length=100)),
                ('image_name', models.CharField(default='N/A', max_length=100)),
                ('group_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('network_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.Network')),
            ],
        ),
        migrations.RemoveField(
            model_name='micro_service',
            name='group_fk',
        ),
        migrations.RemoveField(
            model_name='micro_service',
            name='image_fk',
        ),
        migrations.RemoveField(
            model_name='micro_service',
            name='network_fk',
        ),
        migrations.DeleteModel(
            name='Micro_service',
        ),
    ]
