# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_service', '0005_auto_20171009_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_catalog',
            name='registry_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='micro_service.Registry'),
        ),
    ]
