# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_service', '0006_container_catalog_registry_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(default='N/A', max_length=20)),
                ('container_catalog_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='micro_service.Container_catalog')),
            ],
        ),
    ]
