# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_node_store_fk'),
        ('micro_service', '0007_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='node_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='node.Node'),
        ),
    ]
