# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_auto_20170822_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=22)),
                ('lan1_method', models.CharField(max_length=8)),
                ('lan1_ip', models.CharField(max_length=20, null=True)),
                ('lan1_netmask', models.CharField(max_length=20, null=True)),
                ('lan1_gateway', models.CharField(max_length=20, null=True)),
                ('dns1_ip', models.CharField(max_length=20)),
                ('dns2_ip', models.CharField(max_length=20, null=True)),
                ('dns_domain', models.CharField(max_length=30, null=True)),
                ('dns_search', models.CharField(max_length=30, null=True)),
                ('group_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
    ]
