# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='group_fk',
        ),
        migrations.AddField(
            model_name='node',
            name='client_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
