# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170822_1530'),
        ('node', '0002_auto_20170825_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='group_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
    ]
