# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_auto_20170825_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
