# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_auto_20170825_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='brand_new',
            field=models.NullBooleanField(),
        ),
    ]
