# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_node_brand_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='lan1_gateway',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lan1_ip',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lan1_method',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lan1_netmask',
        ),
    ]
