# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('node', '0008_auto_20170828_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='store_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
