# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_node_store_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='dns1_ip',
        ),
        migrations.RemoveField(
            model_name='node',
            name='dns2_ip',
        ),
        migrations.RemoveField(
            model_name='node',
            name='dns_domain',
        ),
        migrations.RemoveField(
            model_name='node',
            name='dns_search',
        ),
    ]
