# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_alias',
            field=models.CharField(default='N/A', max_length=3),
        ),
    ]
