# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_auto_20170822_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall_rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name_text', models.CharField(max_length=150)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('proto', models.CharField(blank=True, max_length=7, null=True)),
                ('chain', models.CharField(blank=True, max_length=10, null=True)),
                ('action', models.CharField(blank=True, max_length=11, null=True)),
                ('table', models.CharField(blank=True, max_length=10, null=True)),
                ('outiface', models.CharField(blank=True, max_length=10, null=True)),
                ('iniface', models.CharField(blank=True, max_length=10, null=True)),
                ('sport', models.IntegerField(blank=True, default=0, null=True)),
                ('dport', models.IntegerField(blank=True, default=0, null=True)),
                ('group_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
    ]
