# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='ip',
            new_name='ipaddress',
        ),
    ]
