# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20170828_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='bridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='network_bridge',
            field=models.BooleanField(default=False),
        ),
    ]
