# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20171002_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_bridge_name',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
