# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_network_network_bridge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_default_gateway',
            field=models.BooleanField(default=False),
        ),
    ]
