# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('group', '0002_auto_20170822_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('client_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('group_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
    ]
