# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
