# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_auto_20170822_1530'),
        ('network', '0003_auto_20170828_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhcp_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.CharField(max_length=150)),
                ('network_range', models.CharField(max_length=150)),
                ('gateway', models.CharField(max_length=150)),
                ('group_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('network_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.Network')),
            ],
        ),
        migrations.CreateModel(
            name='Dhcp_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameservers', models.CharField(max_length=150)),
                ('ntpservers', models.CharField(max_length=150)),
                ('interfaces', models.CharField(max_length=150)),
                ('pxeserver', models.CharField(max_length=150)),
                ('group_fk', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
    ]
