# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp_service',
            name='dnsdomain',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
