# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_dhcp_service_dnsdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp_service',
            name='pxefilename',
            field=models.CharField(default='pxelinux.0', max_length=150),
        ),
    ]
