# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_auto_20170828_1726'),
        ('dhcp', '0003_dhcp_service_pxefilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcp_pool',
            name='group_fk',
        ),
        migrations.AddField(
            model_name='dhcp_pool',
            name='node_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='node.Node'),
        ),
    ]
