# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0005_auto_20170831_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp_pool',
            name='domain',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='dhcp_pool',
            name='network',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
